mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('posts/', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

from posts.views import (
  ListPostView,
)

app_name='posts'

urlpatterns = [
    # path('list-posts/$', ListPostView.as_view(), name='list-posts'),
    path('', ListPostView.as_view(), name='list-posts'),
]

posts/models.py
from __future__ import unicode_literals
from django.template.defaultfilters import slugify
from django.db import models
# from django.core.urlresolvers import reverse

class Post(models.Model):
  name = models.CharField(max_length=224, null=False, blank=False)
  content = models.TextField(max_length=5000, null=False, blank=False)
  slug = models.SlugField(max_length=255)
  timestamp = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)

  def __unicode__(self):
    return self.content
  
  def save(self, *args, **kwargs):
    if not self.slug:
      self.slug = slugify(self.name)
    super(Post, self).save(*args, **kwargs)

posts/views.py
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.views.generic import ListView

from .models import Post

class ListPostView(ListView):
  model = Post
  def get (self, request, *args, **kwargs):
    template_name = 'posts/list-posts.html' # sẽ được tạo ở phần dưới
    obj = {
      'posts': Post.objects.all()
    }
    return render(request, template_name, obj)

posts/templates/layouts/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}CRUD{% endblock title %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <style>
          footer {
            background-color: #555;
            color: white;
            padding: 15px;
          }
        </style>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row content">
              <!-- <div class="col-sm-3 sidenav">
                <h4>CRUD</h4>
                <ul class="nav nav-pills nav-stacked">
                  <li {% if request.path == "/posts/list-posts/" %}class="active"{% endif %}>
                    <a href="{% url 'posts:list-posts' %}">List Posts</a>
                  </li>
                </ul><br>
              </div>         -->
              <div class="col-sm-12">
                  {% block content %}
                  {% endblock content %}
              </div>
            </div>
          </div>          
          <!-- <footer class="container-fluid">
            <p>My Project CRUD Posts</p>
          </footer> -->
    </body>
</html>

posts/templates/posts/list-posts.html
{% extends "layouts/layout.html" %}
{% block title %}
    List Post | {{ block.super }}
{% endblock title %}
{% block content %}
  <h4><small>List Posts</small></h4>
  <hr>
  {% if posts %}
    {% for post in posts %}
    <div>
        <div data-toggle="collapse" data-target="#{{post.id}}">
            <h2>{{post.name}}</h2>
            <h5><span class="glyphicon glyphicon-time"></span> Post at {{post.timestamp}}</h5>
        </div>
        <div id="{{post.id}}" class="collapse">
            <p>{{post.content}}</p>
        </div> 
    </div>
    <br><br>
    {% endfor %}
  {% else %}
    No song.
  {% endif %}
{% endblock content %}